name: Native Android Build
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies
        run: npm install

      - name: Run Expo Prebuild
        id: prebuild_first
        continue-on-error: true
        run: npx expo prebuild -p android

      - name: Fix build.gradle if prebuild failed
        if: steps.prebuild_first.outcome == 'failure'
        run: |
          BUILD_GRADLE_PATH="android/app/build.gradle"
          if ! grep -q "applyNativeModulesAppBuildGradle(project)" $BUILD_GRADLE_PATH; then
            sed -i '1i applyNativeModulesAppBuildGradle(project)' $BUILD_GRADLE_PATH
            echo "Added applyNativeModulesAppBuildGradle(project) at line 1 of build.gradle"
          else
            echo "applyNativeModulesAppBuildGradle(project) already exists in build.gradle"
          fi
          npx expo prebuild -p android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          BUILD_TYPE="${{ inputs.build_type || 'release' }}"
          if [ "$BUILD_TYPE" = "release" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ inputs.build_type || 'release' }}-${{ github.ref_name || github.sha }}
          path: android/app/build/outputs/apk/**/*.apk
