name: Nightly Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-commit-info:
    name: Get Commit Info
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.commit.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Call Build Apps Workflow
    needs: get-commit-info
    uses: ./.github/workflows/build-apps.yml
    with:
      platform: both
      android_profile: production
      ios_build_type: release
      build_suffix: _nightly-${{ needs.get-commit-info.outputs.sha_short }}
    secrets: inherit
